### ISSUE TITLE
multihop simulator

### ISSUE THREAD

**Issue by absentio** [DRAMCO/LoRaMultiHop#1]
Hi,
I can't find the multihop simulator mentioned in your paper. Where can I retrieve it?

**Comment by guusleenders** [comment]
Hi! You can find the multihop simulator in this github repo: [github.com/DRAMCO/LoRa-multihop-simulator](https://github.com/DRAMCO/LoRa-multihop-simulator)

**Comment by absentio** [comment]
Thanks a lot. Is there any documentation on that? Some of the files won't run because of errors

**Comment by GillesC** [comment]
I will close this issue, as the links to the simulator are provided in the repo. Simulator specific issues should be opened in the corresponding repository.
